version: "3"

services:
    api:
        
        container_name: test_lapisco_trainee_api_iris_fastapi
        build:
            context: .
            dockerfile: Dockerfile
        ports: 
            - $PORT:80
        env_file: .env
        
        restart: always